#!/usr/bin/env bash
# Sync this machine's current config BACK INTO the repo (reverse of install).
# Run it before migrating/wiping a machine so the repo stays an up-to-date mirror,
# then review `git diff`, commit, and push.
#
#   ./scripts/dump.sh        (or)   ./install.sh --only dump
set -euo pipefail
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib.sh"

log "Dump — syncing this machine's config into the repo"
load_brew

# Resolve a path to its real location (handles symlinks). Falls back to the path.
resolve() { python3 -c 'import os,sys; print(os.path.realpath(sys.argv[1]))' "$1" 2>/dev/null || echo "$1"; }

# Copy live → repo, UNLESS the live file is already a symlink to the repo file
# (on a provisioned machine the dotfiles are symlinks — nothing to copy).
sync_file() {
  local live="$1" repo="$2"
  if [[ ! -e "$live" ]]; then warn "skip (absent): ${live/#$HOME/~}"; return; fi
  if [[ "$(resolve "$live")" == "$(resolve "$repo")" ]]; then skip "${live/#$HOME/~} (already linked)"; return; fi
  mkdir -p "$(dirname "$repo")"
  cp -f "$live" "$repo"
  ok "synced ${live/#$HOME/~}"
}

# --- 1. Homebrew: full machine dump → Brewfile.machine ---------------------
# Never clobbers the curated Brewfile; this is a complete snapshot for reference.
if has brew; then
  brew bundle dump --force --file="$REPO_ROOT/Brewfile.machine"
  n="$(grep -cE '^(brew|cask|tap|mas|vscode) ' "$REPO_ROOT/Brewfile.machine" || true)"
  ok "wrote Brewfile.machine ($n entries) — diff against Brewfile to promote anything you want by default"
fi

# --- 2. Dotfiles (skipped automatically when already symlinked) ------------
sync_file "$HOME/.zshrc"                       "$REPO_ROOT/dotfiles/zsh/.zshrc"
sync_file "$HOME/.zshenv"                       "$REPO_ROOT/dotfiles/zsh/.zshenv"
sync_file "$HOME/.config/starship.toml"         "$REPO_ROOT/dotfiles/starship/.config/starship.toml"
sync_file "$HOME/.config/mise/config.toml"      "$REPO_ROOT/dotfiles/mise/.config/mise/config.toml"
sync_file "$HOME/.config/aerospace/aerospace.toml" "$REPO_ROOT/dotfiles/aerospace/.config/aerospace/aerospace.toml"
# NOTE: ~/.gitconfig is intentionally NOT dumped — the repo copy is curated and
#       your identity lives in the untracked ~/.gitconfig.local.

# --- 3. SketchyBar (whole directory) ---------------------------------------
SB_LIVE="$HOME/.config/sketchybar"
SB_REPO="$REPO_ROOT/dotfiles/sketchybar/.config/sketchybar"
if [[ -L "$SB_LIVE" || "$(resolve "$SB_LIVE")" == "$(resolve "$SB_REPO")" ]]; then
  skip "sketchybar config (already linked)"
elif [[ -d "$SB_LIVE" ]]; then
  rsync -a --delete --exclude '.DS_Store' "$SB_LIVE"/ "$SB_REPO"/
  find "$SB_REPO" -name '*.sh' -exec chmod +x {} + 2>/dev/null || true
  [[ -f "$SB_REPO/sketchybarrc" ]] && chmod +x "$SB_REPO/sketchybarrc"
  ok "synced ~/.config/sketchybar"
fi

# --- 4. VS Code extensions -------------------------------------------------
if has code; then
  {
    echo "# VS Code extensions — one id per line. Regenerated by scripts/dump.sh."
    code --list-extensions | sort
  } > "$REPO_ROOT/vscode/extensions.txt"
  ok "synced VS Code extensions ($(code --list-extensions | wc -l | tr -d ' '))"
fi
# settings.json / keybindings.json are symlinked into the repo by vscode.sh,
# so edits made in the app are already saved here — nothing to dump.

log "Dump complete"
info "Review:  git -C \"$REPO_ROOT\" status && git -C \"$REPO_ROOT\" diff"
info "Then:    git -C \"$REPO_ROOT\" add -A && git commit -m \"sync config\" && git push"
